server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.131:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_wms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
  rabbitmq:
    host: 106.54.238.192
    username: gmall
    password: gmall
    virtual-host: /gmall
        
mybatis-plus:
  global-config:
    db-config:
      id-type: auto